version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-nopass
    environment:
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/var/lib/postgresql/data/postgresql.conf'